

package ic2;

import ic2.IC2;
import ic2.IC2Blocks;
import ic2.IC2Config;
import ic2.item.ItemBattery;
import ic2.item.ItemCablePlaceable;
import ic2.item.ItemDynamite;
import ic2.item.ItemFuelCan;
import ic2.item.ItemGradual;
import ic2.item.ItemIC2;
import ic2.item.ItemReinforcedDoor;
import ic2.item.ItemRemote;
import ic2.item.ItemScanner;
import ic2.item.ItemScrapBox;
import ic2.item.ItemTFBPPlaceable;
import ic2.item.armor.IC2Armor;
import ic2.item.armor.ItemArmorChargeable;
import ic2.item.armor.ItemArmorNano;
import ic2.item.armor.ItemArmorJetpackSuit;
import ic2.item.armor.ItemArmorQuantum;
import ic2.item.tool.BronzeTools;
import ic2.item.tool.ItemChainsaw;
import ic2.item.tool.ItemDrill;
import ic2.item.tool.ItemEUReader;
import ic2.item.tool.ItemElectricWrench;
import ic2.item.tool.ItemInsulationCutter;
import ic2.item.tool.ItemMiningLaser;
import ic2.item.tool.ItemNanoSaber;
import ic2.item.tool.ItemPainter;
import ic2.item.tool.ItemTreetap;
import ic2.item.tool.ItemWrench;
import net.minecraft.core.enums.HumanArmorShape;
import net.minecraft.core.enums.IArmorShape;
import net.minecraft.core.enums.WolfArmorShape;
import net.minecraft.core.item.Item;
import net.minecraft.core.item.ItemArmor;
import net.minecraft.core.item.ItemFood;

public class IC2Items {
    public static Item dustCoal;
    public static Item dustIron;
    public static Item dustGold;
    public static Item dustCopper;
    public static Item dustTin;
    public static Item dustBronze;
    public static Item dustSteel;
    public static Item dustSilver;
    public static Item dustLead;
    public static Item dustUranium;
    public static Item dustIronSmall;
    public static Item dustGoldSmall;
    public static Item dustCopperSmall;
    public static Item dustTinSmall;
    public static Item dustBronzeSmall;
    public static Item dustSteelSmall;
    public static Item rawCopper;
    public static Item rawTin;
    public static Item ingotRefinedIron;
    public static Item ingotCopper;
    public static Item ingotTin;
    public static Item ingotBronze;
    public static Item ingotMixedMetal;
    public static Item ingotUran;
    public static Item uraniumItem;
    public static ItemBattery batteryRE;
    public static ItemBattery batteryCrystal;
    public static ItemBattery batteryLamaCrystal;
    public static Item singleUseBattery;
    public static Item cellEmpty;
    public static Item cellLava;
    public static Item cellCoalfuel;
    public static Item cellBiofuel;
    public static Item cellHydratedCoal;
    public static Item cellBiomass;
    public static Item cellWater;
    public static Item cellUran;
    public static Item cellCoolant;
    public static Item cellDepletedIsotope;
    public static Item cellReEnrichedUranium;
    public static Item cellNearDepletedUranium;
    public static Item cellElectrolyzedWater;
    public static ItemDrill miningDrill;
    public static ItemDrill diamondDrill;
    public static ItemChainsaw chainsaw;
    public static Item toolMiningLaser;
    public static Item nanoSaber;
    public static Item nanoSaberOff;
    public static Item wrench;
    public static Item electricWrench;
    public static Item euReader;
    public static Item painter;
    public static Item[] painters;
    public static Item insulationCutter;
    public static ItemTreetap treetap;
    public static Item odScanner;
    public static Item ovScanner;
    public static Item frequencyTransmitter;
    public static Item bronzePickaxe;
    public static Item bronzeAxe;
    public static Item bronzeSword;
    public static Item bronzeShovel;
    public static Item bronzeHoe;
    public static Item fuelCanEmpty;
    public static Item fuelCanFilled;
    public static Item hydratedCoalDust;
    public static Item hydratedCoal;
    public static Item plantball;
    public static Item compressedPlants;
    public static Item tinCan;
    public static Item filledTinCan;
    public static Item dynamiteItem;
    public static Item stickyDynamite;
    public static Item dynamiteOMote;
    public static Item stickyResin;
    public static Item rubber;
    public static Item rubberBoots;
    public static ItemArmorChargeable jetpack;
    public static ItemArmorChargeable electricJetpack;
    public static ItemArmorChargeable jetpackNano;
    public static ItemArmorChargeable electricJetpackNano;
    public static ItemArmorChargeable jetpackQuantum;
    public static ItemArmorChargeable electricJetpackQuantum;
    public static ItemArmorChargeable batpack;
    public static Item bronzeWolfArmor;
    public static Item compositeVest;
    public static Item nanoHelmet;
    public static Item nanoBodyarmor;
    public static Item nanoLeggings;
    public static Item nanoBoots;
    public static Item quantumHelmet;
    public static Item quantumBodyarmor;
    public static Item quantumLeggings;
    public static Item quantumBoots;
    public static Item bronzeHelmet;
    public static Item bronzeChestplate;
    public static Item bronzeLeggings;
    public static Item bronzeBoots;
    public static Item circuit;
    public static Item circuitAdvanced;
    public static Item scrap;
    public static Item uuMatter;
    public static Item advancedAlloy;
    public static Item industrialCredit;
    public static Item reinforcedDoorItem;
    public static Item bronzeDoorItem;
    public static Item reactorPlating;
    public static Item heatDisperser;
    public static Item rawCarbonFibre;
    public static Item rawCarbonMesh;
    public static Item carbonPlate;
    public static Item iridiumPlate;
    public static Item industrialDiamond;
    public static Item coalBall;
    public static Item compressedCoalBall;
    public static Item coalChunk;
    public static Item scrapBox;
    public static Item tfbpEmpty;
    public static Item tfbpCultivation;
    public static Item tfbpIrrigation;
    public static Item tfbpChilling;
    public static Item tfbpDesertification;
    public static Item tfbpFlatification;
    public static Item turbine;
    public static Item woodGasCell;
    public static Item rareEarthDust;
    public static Item rareEarthChuck;
    public static Item deadMagnet;
    public static Item magnet;
    public static Item plasmaCell;
    public static Item plasmaCore;
    public static ItemBattery pesd;
    public static ItemCablePlaceable[] cableItems;
    private static final String[] CABLE_NAMES;
    private static final String[] CABLE_TEX;
    private static final String[] CABLE_KEYS;

    public static void init() {
        int i;
        dustCoal = new ItemIC2("ic2.dust.coal", IC2.key("coal_dust"), IC2Config.item("dust_coal"));
        dustIron = new ItemIC2("ic2.dust.iron", IC2.key("iron_dust"), IC2Config.item("dust_iron"));
        dustGold = new ItemIC2("ic2.dust.gold", IC2.key("gold_dust"), IC2Config.item("dust_gold"));
        dustCopper = new ItemIC2("ic2.dust.copper", IC2.key("copper_dust"), IC2Config.item("dust_copper"));
        dustTin = new ItemIC2("ic2.dust.tin", IC2.key("tin_dust"), IC2Config.item("dust_tin"));
        dustBronze = new ItemIC2("ic2.dust.bronze", IC2.key("bronze_dust"), IC2Config.item("dust_bronze"));
        dustSteel = new ItemIC2("ic2.dust.steel", IC2.key("steel_dust"), IC2Config.item("dust_steel"));
        dustSilver = new ItemIC2("ic2.dust.silver", IC2.key("silver_dust"), IC2Config.item("dust_silver"));
        dustLead = new ItemIC2("ic2.dust.lead", IC2.key("lead_dust"), IC2Config.item("dust_lead"));
        dustUranium = new ItemIC2("ic2.dust.uranium", IC2.key("uranium_dust"), IC2Config.item("dust_uranium"));
        dustIronSmall = new ItemIC2("ic2.dust.iron.small", IC2.key("small_iron_dust"), IC2Config.item("dust_iron_small"));
        dustGoldSmall = new ItemIC2("ic2.dust.gold.small", IC2.key("small_gold_dust"), IC2Config.item("dust_gold_small"));
        dustCopperSmall = new ItemIC2("ic2.dust.copper.small", IC2.key("small_copper_dust"), IC2Config.item("dust_copper_small"));
        dustTinSmall = new ItemIC2("ic2.dust.tin.small", IC2.key("small_tin_dust"), IC2Config.item("dust_tin_small"));
        dustBronzeSmall = new ItemIC2("ic2.dust.bronze.small", IC2.key("small_bronze_dust"), IC2Config.item("dust_bronze_small"));
        dustSteelSmall = new ItemIC2("ic2.dust.steel.small", IC2.key("small_steel_dust"), IC2Config.item("dust_steel_small"));
        rawCopper = new ItemIC2("ic2.ore.raw.copper", IC2.key("raw_copper"), IC2Config.item("raw_copper"));
        rawTin = new ItemIC2("ic2.ore.raw.tin", IC2.key("raw_tin"), IC2Config.item("raw_tin"));
        ingotRefinedIron = new ItemIC2("ic2.ingot.refined_iron", IC2.key("refined_iron"), IC2Config.item("refined_iron"));
        ingotCopper = new ItemIC2("ic2.ingot.copper", IC2.key("copper_ingot"), IC2Config.item("ingot_copper"));
        ingotTin = new ItemIC2("ic2.ingot.tin", IC2.key("tin_ingot"), IC2Config.item("ingot_tin"));
        ingotBronze = new ItemIC2("ic2.ingot.bronze", IC2.key("bronze_ingot"), IC2Config.item("ingot_bronze"));
        ingotMixedMetal = new ItemIC2("ic2.ingot.mixed_metal", IC2.key("mixed_metal_ingot"), IC2Config.item("ingot_mixed_metal"));
        ingotUran = new ItemIC2("ic2.ingot.uranium", IC2.key("refined_uranium"), IC2Config.item("ingot_uranium"));
        uraniumItem = new ItemIC2("ic2.ore.uranium", IC2.key("uranium_ore_item"), IC2Config.item("uranium_item"));
        batteryRE = new ItemBattery("ic2.battery.re", IC2.key("re_battery"), IC2Config.item("re_battery"), 1, 250, true, 1);
        batteryCrystal = new ItemBattery("ic2.battery.crystal", IC2.key("energy_crystal"), IC2Config.item("energy_crystal"), 10, 2500, true, 2);
        batteryLamaCrystal = new ItemBattery("ic2.battery.lapotron", IC2.key("lapotron_crystal"), IC2Config.item("lapotron_crystal"), 100, 60000, true, 3);
        singleUseBattery = new ItemIC2("ic2.battery.single_use", IC2.key("single_use_battery"), IC2Config.item("single_use_battery"));
        cellEmpty = new ItemIC2("ic2.cell.empty", IC2.key("empty_cell"), IC2Config.item("cell_empty"));
        cellLava = new ItemIC2("ic2.cell.lava", IC2.key("lava_cell"), IC2Config.item("cell_lava"));
        cellCoalfuel = new ItemIC2("ic2.cell.coalfuel", IC2.key("coalfuel_cell"), IC2Config.item("cell_coalfuel"));
        cellBiofuel = new ItemIC2("ic2.cell.biofuel", IC2.key("biofuel_cell"), IC2Config.item("cell_biofuel"));
        cellHydratedCoal = new ItemIC2("ic2.cell.hydrated_coal", IC2.key("coalfuel_cell_raw"), IC2Config.item("cell_hydrated_coal"));
        cellBiomass = new ItemIC2("ic2.cell.biomass", IC2.key("biofuel_cell_raw"), IC2Config.item("cell_biomass"));
        cellWater = new ItemIC2("ic2.cell.water", IC2.key("water_cell"), IC2Config.item("cell_water"));
        cellUran = new ItemGradual("ic2.cell.uranium", IC2.key("uranium_cell"), IC2Config.item("cell_uranium"));
        cellCoolant = new ItemGradual("ic2.cell.coolant", IC2.key("coolant_cell"), IC2Config.item("cell_coolant"));
        cellDepletedIsotope = new ItemIC2("ic2.cell.depleted_isotope", IC2.key("depleted_isotope_cell"), IC2Config.item("cell_depleted_isotope")).setMaxStackSize(1);
        cellReEnrichedUranium = new ItemIC2("ic2.cell.reenriched_uranium", IC2.key("reenriched_uranium_cell"), IC2Config.item("cell_reenriched_uranium"));
        cellNearDepletedUranium = new ItemIC2("ic2.cell.near_depleted_uranium", IC2.key("near_depleted_uranium_cell"), IC2Config.item("cell_near_depleted_uranium"));
        cellElectrolyzedWater = new ItemIC2("ic2.cell.electrolyzed_water", IC2.key("electrolyzed_water_cell"), IC2Config.item("cell_electrolyzed_water"));
        miningDrill = new ItemDrill("ic2.tool.drill", IC2.key("mining_drill"), IC2Config.item("mining_drill"), false);
        diamondDrill = new ItemDrill("ic2.tool.drill.diamond", IC2.key("diamond_drill"), IC2Config.item("diamond_drill"), true);
        chainsaw = new ItemChainsaw("ic2.tool.chainsaw", IC2.key("chainsaw"), IC2Config.item("chainsaw"));
        toolMiningLaser = new ItemMiningLaser("ic2.tool.mining_laser", IC2.key("mining_laser"), IC2Config.item("mining_laser"));
        nanoSaber = new ItemNanoSaber("ic2.tool.nano_saber", IC2.key("nano_saber"), IC2Config.item("nano_saber"), true);
        nanoSaberOff = new ItemNanoSaber("ic2.tool.nano_saber.off", IC2.key("nano_saber_off"), IC2Config.item("nano_saber_off"), false);
        wrench = new ItemWrench("ic2.tool.wrench", IC2.key("wrench"), IC2Config.item("wrench"));
        electricWrench = new ItemElectricWrench("ic2.tool.wrench.electric", IC2.key("wrench_electric"), IC2Config.item("electric_wrench"));
        euReader = new ItemEUReader("ic2.tool.eu_reader", IC2.key("eu_reader"), IC2Config.item("eu_reader"));
        painter = new ItemIC2("ic2.tool.painter", IC2.key("painter"), IC2Config.item("painter"));
        String[] painterColors = new String[]{"black", "red", "green", "brown", "blue", "purple", "cyan", "light_gray", "gray", "pink", "lime", "yellow", "light_blue", "magenta", "orange", "white"};
        for (i = 0; i < 16; ++i) {
            IC2Items.painters[i] = new ItemPainter("ic2.tool.painter." + painterColors[i], IC2.key("painter_" + painterColors[i]), IC2Config.item("painter_" + painterColors[i]), i);
        }
        insulationCutter = new ItemInsulationCutter("ic2.tool.insulation_cutter", IC2.key("insulation_cutter"), IC2Config.item("insulation_cutter"));
        treetap = new ItemTreetap("ic2.tool.treetap", IC2.key("treetap"), IC2Config.item("treetap"));
        odScanner = new ItemScanner("ic2.scanner.od", IC2.key("od_scanner"), IC2Config.item("od_scanner"), 1);
        ovScanner = new ItemScanner("ic2.scanner.ov", IC2.key("ov_scanner"), IC2Config.item("ov_scanner"), 2);
        frequencyTransmitter = new ItemIC2("ic2.frequency_transmitter", IC2.key("frequency_transmitter"), IC2Config.item("frequency_transmitter"));
        fuelCanEmpty = new ItemIC2("ic2.fuel_can.empty", IC2.key("fuel_can_empty"), IC2Config.item("fuel_can_empty")).setMaxStackSize(1);
        fuelCanFilled = new ItemFuelCan("ic2.fuel_can.filled", IC2.key("fuel_can_filled"), IC2Config.item("fuel_can_filled")).setContainerItem(null);
        hydratedCoalDust = new ItemIC2("ic2.fuel.hydrated_coal_dust", IC2.key("hydrated_coal_dust"), IC2Config.item("hydrated_coal_dust"));
        hydratedCoal = new ItemIC2("ic2.fuel.hydrated_coal", IC2.key("hydrated_coal"), IC2Config.item("hydrated_coal"));
        plantball = new ItemIC2("ic2.fuel.plantball", IC2.key("plantball"), IC2Config.item("plantball"));
        compressedPlants = new ItemIC2("ic2.fuel.compressed_plants", IC2.key("compressed_plants"), IC2Config.item("compressed_plants"));
        tinCan = new ItemIC2("ic2.tin_can", IC2.key("tin_can"), IC2Config.item("tin_can"));
        filledTinCan = new ItemFood("ic2.tin_can.filled", IC2.key("filled_tin_can"), IC2Config.item("filled_tin_can"), 2, 8, false, 64);
        dynamiteItem = new ItemDynamite("ic2.dynamite", IC2.key("dynamite"), IC2Config.item("dynamite_item"), false);
        stickyDynamite = new ItemDynamite("ic2.dynamite.sticky", IC2.key("sticky_dynamite"), IC2Config.item("sticky_dynamite"), true);
        dynamiteOMote = new ItemRemote("ic2.dynamite_o_mote", IC2.key("dynamite_o_mote"), IC2Config.item("dynamite_o_mote"));
        stickyResin = new ItemIC2("ic2.sticky_resin", IC2.key("sticky_resin"), IC2Config.item("sticky_resin"));
        rubber = new ItemIC2("ic2.rubber", IC2.key("rubber"), IC2Config.item("rubber"));
        rubberBoots = new IC2Armor.RubberBoots("ic2.armor.rubber_boots", IC2.key("rubber_boots"), IC2Config.item("rubber_boots"));
        jetpack = new ItemArmorChargeable("ic2.armor.jetpack", IC2.key("jetpack"), IC2Config.item("jetpack"), IC2Armor.JETPACK, HumanArmorShape.CHEST, 1, 0, 1, 18000);
        electricJetpack = new ItemArmorChargeable("ic2.armor.jetpack.electric", IC2.key("electric_jetpack"), IC2Config.item("electric_jetpack"), IC2Armor.JETPACK, HumanArmorShape.CHEST, 1, 0, 1, 30000);
        batpack = new ItemArmorChargeable("ic2.armor.batpack", IC2.key("batpack"), IC2Config.item("batpack"), IC2Armor.BATPACK, HumanArmorShape.CHEST, 100, 0, 1, 60000);
        compositeVest = new IC2Armor.Composite("ic2.armor.composite_vest", IC2.key("composite_vest"), IC2Config.item("composite_vest"));
        bronzeHelmet = new IC2Armor.Bronze("ic2.armor.bronze.helmet", IC2.key("bronze_helmet"), IC2Config.item("bronze_helmet"), HumanArmorShape.HEAD);
        bronzeChestplate = new IC2Armor.Bronze("ic2.armor.bronze.chestplate", IC2.key("bronze_chestplate"), IC2Config.item("bronze_chestplate"), HumanArmorShape.CHEST);
        bronzeLeggings = new IC2Armor.Bronze("ic2.armor.bronze.leggings", IC2.key("bronze_leggings"), IC2Config.item("bronze_leggings"), HumanArmorShape.LEGS);
        bronzeBoots = new IC2Armor.Bronze("ic2.armor.bronze.boots", IC2.key("bronze_boots"), IC2Config.item("bronze_boots"), HumanArmorShape.BOOTS);
        bronzeWolfArmor = new ItemArmor("ic2.armor.bronze.wolf", IC2.key("armor_wolf_bronze"), IC2Config.item("armor_wolf_bronze"), IC2Armor.BRONZE, (IArmorShape)WolfArmorShape.BODY);

        try {
            net.minecraft.core.entity.animal.MobWolf.ARMOR_MATERIALS.put(IC2Armor.BRONZE, (net.minecraft.core.item.IArmorItem)bronzeWolfArmor);
            IC2.LOGGER.info("Bronze wolf armor registered for wolves");
        } catch (Throwable t) {
            IC2.LOGGER.warn("Failed to register bronze wolf armor for wolves: {}", (Object)t.toString());
        }
        nanoHelmet = new ItemArmorNano("ic2.armor.nano.helmet", IC2.key("nanosuit_helmet"), IC2Config.item("nanosuit_helmet"), HumanArmorShape.HEAD);
        nanoBodyarmor = new ItemArmorNano("ic2.armor.nano.bodyarmor", IC2.key("nanosuit_bodyarmor"), IC2Config.item("nanosuit_bodyarmor"), HumanArmorShape.CHEST);
        nanoLeggings = new ItemArmorNano("ic2.armor.nano.leggings", IC2.key("nanosuit_leggings"), IC2Config.item("nanosuit_leggings"), HumanArmorShape.LEGS);
        nanoBoots = new ItemArmorNano("ic2.armor.nano.boots", IC2.key("nanosuit_boots"), IC2Config.item("nanosuit_boots"), HumanArmorShape.BOOTS);
        quantumHelmet = new ItemArmorQuantum("ic2.armor.quantum.helmet", IC2.key("quantum_helmet"), IC2Config.item("quantum_helmet"), HumanArmorShape.HEAD);
        quantumBodyarmor = new ItemArmorQuantum("ic2.armor.quantum.bodyarmor", IC2.key("quantum_bodyarmor"), IC2Config.item("quantum_bodyarmor"), HumanArmorShape.CHEST);
        quantumLeggings = new ItemArmorQuantum("ic2.armor.quantum.leggings", IC2.key("quantum_leggings"), IC2Config.item("quantum_leggings"), HumanArmorShape.LEGS);
        quantumBoots = new ItemArmorQuantum("ic2.armor.quantum.boots", IC2.key("quantum_boots"), IC2Config.item("quantum_boots"), HumanArmorShape.BOOTS);
        jetpackNano = new ItemArmorJetpackSuit("ic2.armor.jetpack.nano", IC2.key("jetpack_nano"), IC2Config.item("jetpack_nano"), false, false, 100000);
        electricJetpackNano = new ItemArmorJetpackSuit("ic2.armor.jetpack.electric.nano", IC2.key("electric_jetpack_nano"), IC2Config.item("electric_jetpack_nano"), false, true, 100000);
        jetpackQuantum = new ItemArmorJetpackSuit("ic2.armor.jetpack.quantum", IC2.key("jetpack_quantum"), IC2Config.item("jetpack_quantum"), true, false, 1000000);
        electricJetpackQuantum = new ItemArmorJetpackSuit("ic2.armor.jetpack.electric.quantum", IC2.key("electric_jetpack_quantum"), IC2Config.item("electric_jetpack_quantum"), true, true, 1000000);
        bronzePickaxe = new BronzeTools.Pickaxe("ic2.tool.bronze.pickaxe", IC2.key("bronze_pickaxe"), IC2Config.item("bronze_pickaxe"));
        bronzeAxe = new BronzeTools.Axe("ic2.tool.bronze.axe", IC2.key("bronze_axe"), IC2Config.item("bronze_axe"));
        bronzeSword = new BronzeTools.Sword("ic2.tool.bronze.sword", IC2.key("bronze_sword"), IC2Config.item("bronze_sword"));
        bronzeShovel = new BronzeTools.Shovel("ic2.tool.bronze.shovel", IC2.key("bronze_shovel"), IC2Config.item("bronze_shovel"));
        bronzeHoe = new BronzeTools.Hoe("ic2.tool.bronze.hoe", IC2.key("bronze_hoe"), IC2Config.item("bronze_hoe"));
        circuit = new ItemIC2("ic2.circuit", IC2.key("electronic_circuit"), IC2Config.item("circuit"));
        circuitAdvanced = new ItemIC2("ic2.circuit.advanced", IC2.key("advanced_circuit"), IC2Config.item("circuit_advanced"));
        scrap = new ItemIC2("ic2.scrap", IC2.key("scrap"), IC2Config.item("scrap"));
        uuMatter = new ItemIC2("ic2.uu_matter", IC2.key("uu_matter"), IC2Config.item("uu_matter"));
        advancedAlloy = new ItemIC2("ic2.advanced_alloy", IC2.key("advanced_alloy"), IC2Config.item("advanced_alloy"));
        industrialCredit = new ItemIC2("ic2.industrial_credit", IC2.key("industrial_credit"), IC2Config.item("industrial_credit"));
        reinforcedDoorItem = new ItemReinforcedDoor("ic2.door.reinforced", IC2.key("reinforced_door"), IC2Config.item("reinforced_door_item"), IC2Blocks.reinforcedDoorBottom, IC2Blocks.reinforcedDoorTop);
        bronzeDoorItem = new ItemReinforcedDoor("ic2.door.bronze", IC2.key("bronze_door"), IC2Config.item("bronze_door_item"), IC2Blocks.bronzeDoorBottom, IC2Blocks.bronzeDoorTop);
        reactorPlating = new ItemGradual("ic2.reactor.plating", IC2.key("reactor_plating"), IC2Config.item("reactor_plating"));
        heatDisperser = new ItemGradual("ic2.reactor.heat_disperser", IC2.key("heat_disperser"), IC2Config.item("heat_disperser"));
        rawCarbonFibre = new ItemIC2("ic2.carbon.raw_fibre", IC2.key("raw_carbon_fibre"), IC2Config.item("raw_carbon_fibre"));
        rawCarbonMesh = new ItemIC2("ic2.carbon.raw_mesh", IC2.key("raw_carbon_mesh"), IC2Config.item("raw_carbon_mesh"));
        carbonPlate = new ItemIC2("ic2.carbon.plate", IC2.key("carbon_plate"), IC2Config.item("carbon_plate"));
        iridiumPlate = new ItemIC2("ic2.iridium_plate", IC2.key("iridium_plate"), IC2Config.item("iridium_plate"));
        industrialDiamond = new ItemIC2("ic2.industrial_diamond", IC2.key("industrial_diamond"), IC2Config.item("industrial_diamond"));
        coalBall = new ItemIC2("ic2.coal_ball", IC2.key("coal_ball"), IC2Config.item("coal_ball"));
        compressedCoalBall = new ItemIC2("ic2.coal_ball.compressed", IC2.key("compressed_coal_ball"), IC2Config.item("compressed_coal_ball"));
        coalChunk = new ItemIC2("ic2.coal_chunk", IC2.key("coal_chunk"), IC2Config.item("coal_chunk"));
        scrapBox = new ItemScrapBox("ic2.scrap_box", IC2.key("scrap_box"), IC2Config.item("scrap_box"));
        tfbpEmpty = new ItemIC2("ic2.tfbp", IC2.key("tfbp_empty"), IC2Config.item("tfbp_empty"));
        tfbpCultivation = new ItemTFBPPlaceable("ic2.tfbp.cultivation", IC2.key("tfbp_cultivation"), IC2Config.item("tfbp_cultivation"));
        tfbpIrrigation = new ItemTFBPPlaceable("ic2.tfbp.irrigation", IC2.key("tfbp_irrigation"), IC2Config.item("tfbp_irrigation"));
        tfbpChilling = new ItemTFBPPlaceable("ic2.tfbp.chilling", IC2.key("tfbp_chilling"), IC2Config.item("tfbp_chilling"));
        tfbpDesertification = new ItemTFBPPlaceable("ic2.tfbp.desertification", IC2.key("tfbp_desertification"), IC2Config.item("tfbp_desertification"));
        tfbpFlatification = new ItemTFBPPlaceable("ic2.tfbp.flatification", IC2.key("tfbp_flatification"), IC2Config.item("tfbp_flatification"));
        turbine = new ItemIC2("ic2.turbine", IC2.key("turbine"), IC2Config.item("turbine"));
        woodGasCell = new ItemIC2("ic2.wood_gas_cell", IC2.key("wood_gas_cell"), IC2Config.item("wood_gas_cell"));
        rareEarthDust = new ItemIC2("ic2.rare_earth_dust", IC2.key("rare_earth_dust"), IC2Config.item("rare_earth_dust"));
        rareEarthChuck = new ItemIC2("ic2.rare_earth_chuck", IC2.key("rare_earth_chuck"), IC2Config.item("rare_earth_chuck"));
        deadMagnet = new ItemIC2("ic2.magnet.dead", IC2.key("dead_magnet"), IC2Config.item("dead_magnet"));
        magnet = new ItemIC2("ic2.magnet", IC2.key("magnet"), IC2Config.item("magnet"));
        plasmaCell = new ItemIC2("ic2.plasma_cell", IC2.key("plasma_cell"), IC2Config.item("plasma_cell"));
        plasmaCore = new ItemIC2("ic2.plasma_core", IC2.key("plasma_core"), IC2Config.item("plasma_core"));
        pesd = new ic2.item.ItemBatteryHeavy("ic2.pesd", IC2.key("pesd"), IC2Config.item("pesd"), 5000, 25000, true, 4, 9999);
        for (i = 0; i < 12; ++i) {
            IC2Items.cableItems[i] = new ItemCablePlaceable("ic2." + CABLE_KEYS[i], IC2.key(CABLE_TEX[i]), IC2Config.item(CABLE_KEYS[i]), i);
        }
    }

    static {
        painters = new Item[16];
        cableItems = new ItemCablePlaceable[12];
        CABLE_NAMES = new String[]{"Copper Cable", "Uninsulated Copper Cable", "Gold Cable", "Insulated Gold Cable", "2xIns. Gold Cable", "HV Cable", "Insulated HV Cable", "2xIns. HV Cable", "4xIns. HV Cable", "Glass Fibre Cable", "Ultra-Low-Current Cable", "Plasma Cable"};
        CABLE_TEX = new String[]{"cable_copper", "cable_copper_uninsulated", "cable_gold", "cable_gold_insulated", "cable_gold_insulated_2x", "cable_hv", "cable_hv_insulated", "cable_hv_insulated_2x", "cable_hv_insulated_4x", "cable_glass_fibre", "cable_tin", "cable_plasma"};
        CABLE_KEYS = CABLE_TEX;
    }
}

